// es-cypfer.js -- EventScope v5 -- Collector script generator
// Renders a ready-to-run PowerShell script for EventScope triage collection.
// Two modes:
//   live   -- run against the host the script is executed on (self-elevates)
//   image  -- run against a mounted forensic image (a C folder)
//
// Output is copied to clipboard / downloaded as .ps1 so the responder can
// paste into VS Code and hit run. Nothing is executed from the browser.
'use strict';

// ── STATE ─────────────────────────────────────────────────────────────────────

const CYPFER_DEFAULTS = {
  mode:        'live',              // 'live' | 'image'
  caseName:    'case-001',
  hostLabel:   'HOSTNAME',
  sourceC:     'D:\\CaseAnalysis\\case-001\\HOSTNAME\\C',
  outDir:      'C:\\eventscope\\output',
  caseDir:     'D:\\CaseAnalysis\\case-001\\HOSTNAME',
  toolsDir:    'C:\\Tools',
};

let _cypferState = { ...CYPFER_DEFAULTS };

// ── TEMPLATE RENDERING ────────────────────────────────────────────────────────

// Escape a user-provided path so it can be safely embedded inside a PowerShell
// double-quoted string literal. Paths must NOT contain " or backticks.
function _psEscape(s) {
  if (!s) return '';
  return String(s).replace(/`/g, '``').replace(/"/g, '`"');
}

function _cypferRenderLive(v) {
  const outDir   = _psEscape(v.outDir);
  const toolsDir = _psEscape(v.toolsDir);
  return `# collect-local.ps1 -- EventScope live system triage
# Generated by EventScope Cypfer tab on ${new Date().toISOString()}
# Self-elevates via UAC.

param(
    [string] $OutDir   = "${outDir}",
    [string] $ToolsDir = "${toolsDir}"
)

# -- SELF-ELEVATION ------------------------------------------------------------

if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "Not running as admin - requesting elevation..."
    $argStr = "-NoProfile -ExecutionPolicy Bypass -File \`"$PSCommandPath\`" -OutDir \`"$OutDir\`" -ToolsDir \`"$ToolsDir\`""
    Start-Process powershell -Verb RunAs -ArgumentList $argStr
    exit
}

$ErrorActionPreference = "Continue"

# -- OUTPUT DIRS ---------------------------------------------------------------

$HivesDir   = Join-Path $OutDir "hives"
$ParsedOS   = Join-Path $OutDir "parsed_os"
$ParsedUser = Join-Path $OutDir "parsed_user"
$SrumDir    = Join-Path $OutDir "srum"

foreach ($d in @($HivesDir, $ParsedOS, $ParsedUser, $SrumDir)) {
    New-Item -ItemType Directory -Path $d -Force | Out-Null
}

# -- TOOL DISCOVERY ------------------------------------------------------------

function Find-Tool {
    param([string]$Dir, [string]$Pattern)
    $hit = Get-ChildItem $Dir -Filter $Pattern -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($hit) { return $hit.FullName }
    return $null
}

$ZimTools = Join-Path $ToolsDir "ZimmermanTools\\net9"
$RipExe   = Find-Tool (Join-Path $ToolsDir "RegRipper3.0") "rip.exe"
$RECmdExe = Find-Tool $ZimTools "RECmd.exe"
$SrumExe  = Find-Tool $ZimTools "SrumECmd.exe"
$SBEExe   = Find-Tool $ZimTools "SBECmd.exe"
$EvtxExe  = Find-Tool $ZimTools "EvtxECmd.exe"
$HayaExe  = Find-Tool (Join-Path $ToolsDir "hayabusa") "hayabusa.exe"

function Run { param([string]$exe, [string[]]$params)
    if (-not $exe -or -not (Test-Path $exe -ErrorAction SilentlyContinue)) {
        Write-Host "  SKIP (not found): $exe"; return
    }
    Write-Host "  RUN: $(Split-Path $exe -Leaf) $($params -join ' ')"
    & $exe @params 2>&1 | ForEach-Object {
        if ($_ -is [System.Management.Automation.ErrorRecord]) {
            Write-Host "  ERR: $_"
        }
    }
}

# -- 1. REGISTRY HIVE COPIES ---------------------------------------------------

Write-Host "\`n[1/7] Saving registry hives..."
foreach ($hive in @("SAM","SOFTWARE","SYSTEM","SECURITY")) {
    $dest = Join-Path $HivesDir $hive
    reg.exe save "HKLM\\$hive" $dest /y 2>&1 | Out-Null
    if (Test-Path $dest) { Write-Host "  OK: $hive" } else { Write-Host "  FAIL: $hive" }
}

Write-Host "\`n  Copying NTUSER.DAT per user via VSS..."
$shadowObj = $null
try {
    $result = (Get-WmiObject -List Win32_ShadowCopy).Create("C:\\", "ClientAccessible")
    if (-not $result -or $result.ReturnValue -ne 0) {
        throw "Win32_ShadowCopy.Create returned $($result.ReturnValue)"
    }
    $shadowObj  = Get-WmiObject Win32_ShadowCopy | Where-Object { $_.ID -eq $result.ShadowID }
    $shadowRoot = $shadowObj.DeviceObject + "\\"
    Write-Host "  VSS snapshot: $shadowRoot"

    Get-ChildItem "C:\\Users" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
        $vssSrc = $shadowRoot + "Users\\" + $_.Name + "\\NTUSER.DAT"
        $dest   = Join-Path $HivesDir ($_.Name + ".NTUSER.DAT")
        if (Test-Path $vssSrc) {
            Copy-Item $vssSrc $dest -Force
            Write-Host "  OK (VSS): $($_.Name)\\NTUSER.DAT"
        }
    }
} catch {
    Write-Host "  VSS failed: $_"
    Get-ChildItem "C:\\Users" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
        $src  = Join-Path $_.FullName "NTUSER.DAT"
        $dest = Join-Path $HivesDir ($_.Name + ".NTUSER.DAT")
        if (Test-Path $src) {
            try { Copy-Item $src $dest -Force; Write-Host "  OK: $($_.Name)\\NTUSER.DAT" }
            catch { Write-Host "  FAIL (locked): $($_.Name)\\NTUSER.DAT" }
        }
    }
} finally {
    if ($shadowObj) { $shadowObj.Delete() | Out-Null; Write-Host "  VSS snapshot deleted." }
}

# -- 2. REGRIPPER --------------------------------------------------------------

Write-Host "\`n[2/7] RegRipper..."
if ($RipExe) {
    foreach ($hive in @("SAM","SOFTWARE","SYSTEM","SECURITY")) {
        $src = Join-Path $HivesDir $hive
        if (Test-Path $src) {
            $out = Join-Path $ParsedOS "\${hive}.rr3.txt"
            & $RipExe -r $src -a 2>$null | Out-File $out -Encoding utf8
            Write-Host "  $hive -> $out"
        }
    }
    Get-ChildItem $HivesDir -Filter "*.NTUSER.DAT" | ForEach-Object {
        $username = $_.Name -replace '\\.NTUSER\\.DAT$',''
        $out = Join-Path $ParsedUser "$username.NTUSER.rr3.txt"
        & $RipExe -r $_.FullName -a 2>$null | Out-File $out -Encoding utf8
        Write-Host "  $username -> $out"
    }
} else { Write-Host "  SKIP - rip.exe not found" }

# -- 3. RECMD ------------------------------------------------------------------

Write-Host "\`n[3/7] RECmd..."
if ($RECmdExe) {
    foreach ($h in @("SOFTWARE","SAM","SYSTEM")) {
        $src = Join-Path $HivesDir $h
        if (Test-Path $src) { Run $RECmdExe @("-f", $src, "--csv", $ParsedOS, "--csvf", "$h.recmd.csv") }
    }
    Get-ChildItem $HivesDir -Filter "*.NTUSER.DAT" | ForEach-Object {
        $username = $_.Name -replace '\\.NTUSER\\.DAT$',''
        Run $RECmdExe @("-f", $_.FullName, "--csv", $ParsedUser, "--csvf", "$username.recmd.csv")
    }
} else { Write-Host "  SKIP - RECmd.exe not found" }

# -- 4. SRUM -------------------------------------------------------------------

Write-Host "\`n[4/7] SrumECmd..."
if ($SrumExe) {
    $sruDb  = "C:\\Windows\\System32\\sru\\SRUDB.dat"
    $swHive = Join-Path $HivesDir "SOFTWARE"
    if (Test-Path $sruDb) {
        $args = @("-f", $sruDb, "--csv", $SrumDir)
        if (Test-Path $swHive) { $args += @("-r", $swHive) }
        Run $SrumExe $args
    } else { Write-Host "  SKIP - SRUDB.dat not found" }
} else { Write-Host "  SKIP - SrumECmd.exe not found" }

# -- 5. SHELLBAGS --------------------------------------------------------------

Write-Host "\`n[5/7] ShellBags..."
if ($SBEExe) {
    Get-ChildItem "C:\\Users" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
        Run $SBEExe @("-d", $_.FullName, "--csv", $ParsedUser, "--csvf", "$($_.Name).shellbags.csv")
    }
} else { Write-Host "  SKIP - SBECmd.exe not found" }

# -- 6. EVENT LOGS -------------------------------------------------------------

Write-Host "\`n[6/7] Event logs..."
if ($EvtxExe) {
    Run $EvtxExe @("-d", "C:\\Windows\\System32\\winevt\\Logs", "--csv", $OutDir, "--csvf", "_EVTX_live-all.csv")
} else { Write-Host "  SKIP - EvtxECmd.exe not found" }

if ($HayaExe) {
    Run $HayaExe @("csv-timeline", "--directory", "C:\\Windows\\System32\\winevt\\Logs", "-s", "-w", "-a", "-b", "-o", (Join-Path $OutDir "Hayabusa-all.csv"), "-p", "standard", "-X", "-U", "-q")
} else { Write-Host "  SKIP - hayabusa.exe not found" }

# -- 7. NETWORK CONFIG ---------------------------------------------------------

Write-Host "\`n[7/7] Network configuration..."
$NetDir = Join-Path $OutDir "network"
New-Item -ItemType Directory -Path $NetDir -Force | Out-Null
Get-NetAdapter -ErrorAction SilentlyContinue | Export-Csv (Join-Path $NetDir 'network-adapters.csv') -NoTypeInformation -Encoding UTF8
Get-ChildItem 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\NetworkList\\Profiles' -ErrorAction SilentlyContinue |
    ForEach-Object { Get-ItemProperty $_.PSPath } |
    Export-Csv (Join-Path $NetDir 'network-profiles.csv') -NoTypeInformation -Encoding UTF8

Write-Host "\`nDone. Output: $OutDir"
Write-Host "Press any key to close..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
`;
}

function _cypferRenderImage(v) {
  const caseName  = _psEscape(v.caseName);
  const hostLabel = _psEscape(v.hostLabel);
  const sourceC   = _psEscape(v.sourceC);
  const caseDir   = _psEscape(v.caseDir);
  const toolsDir  = _psEscape(v.toolsDir);
  return `# collect-image.ps1 -- EventScope triage against a mounted forensic image
# Generated by EventScope Cypfer tab on ${new Date().toISOString()}
# Run from an elevated PowerShell prompt.

$CaseName = "${caseName}"
$Host     = "${hostLabel}"
$SrcC     = "${sourceC}"
$CaseDir  = "${caseDir}"
$ToolsDir = "${toolsDir}"

$OutDir         = Join-Path $CaseDir $Host
$ParsedOSHives  = Join-Path $OutDir "ParsedOSHives"
$ParsedUserHives = Join-Path $OutDir "ParsedUserHives"
$ScriptBlocksDir = Join-Path $OutDir "PSScriptBlocks"

foreach ($d in @($OutDir, $ParsedOSHives, $ParsedUserHives, $ScriptBlocksDir)) {
    New-Item -ItemType Directory -Path $d -Force | Out-Null
}

# -- Tool paths ---------------------------------------------------------------
$RipExe     = Join-Path $ToolsDir "RegRipper3.0\\rip.exe"
$SBEExe     = Join-Path $ToolsDir "ZimmermanTools\\SBECmd.exe"
$AppCompat  = Join-Path $ToolsDir "ZimmermanTools\\AppCompatCacheParser.exe"
$EvtxExe    = Join-Path $ToolsDir "ZimmermanTools\\EvtxeCmd\\EvtxECmd.exe"
$Amcache    = Join-Path $ToolsDir "ZimmermanTools\\AmcacheParser.exe"
$SumExe     = Join-Path $ToolsDir "ZimmermanTools\\SumECmd.exe"
$SrumExe    = Join-Path $ToolsDir "ZimmermanTools\\SrumECmd.exe"
$MFTExe     = Join-Path $ToolsDir "ZimmermanTools\\MFTECmd.exe"
$SidrExe    = Join-Path $ToolsDir "sidr.exe"
$ChainsawExe = Join-Path $ToolsDir "chainsaw\\chainsaw.exe"
$HayaExe    = Join-Path $ToolsDir "hayabusa\\hayabusa.exe"
$TakajoExe  = Join-Path $ToolsDir "Takajo\\takajo.exe"
$PyWmi      = Join-Path $ToolsDir "PyWMIPersistenceFinder.py"
$PyCcm      = Join-Path $ToolsDir "CCM_RUA_Finder.py"
$Py27       = "C:\\Python27\\python.exe"

function Run { param([string]$exe, [string[]]$params)
    if (-not $exe -or -not (Test-Path $exe -ErrorAction SilentlyContinue)) {
        Write-Host "  SKIP (not found): $exe"; return
    }
    Write-Host "  RUN: $(Split-Path $exe -Leaf) $($params -join ' ')"
    & $exe @params 2>&1 | Out-Host
}

# -- 1. SHELLBAGS + USER HIVES ------------------------------------------------
Write-Host "\`n[1/9] Shellbags + user hives..."
Get-ChildItem (Join-Path $SrcC "Users") -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    $u = $_.Name
    Run $SBEExe @("-d", $_.FullName, "--csv", $ParsedUserHives, "--csvf", "$u.sbecmd.csv")
    $ntuser = Join-Path $_.FullName "NTUSER.DAT"
    if (Test-Path $ntuser) {
        & $RipExe -r $ntuser -a 2>$null |
            Out-File (Join-Path $ParsedUserHives "$u.NTUSER.dat.rr3.txt") -Encoding utf8
    }
}

# -- 2. OS HIVES --------------------------------------------------------------
Write-Host "\`n[2/9] OS hives..."
$cfgDir = Join-Path $SrcC "Windows\\System32\\config"
foreach ($hive in @("SAM","SOFTWARE","SYSTEM","SECURITY")) {
    $src = Join-Path $cfgDir $hive
    if (Test-Path $src) {
        & $RipExe -r $src -a 2>$null | Out-File (Join-Path $ParsedOSHives "$hive.rr3.txt") -Encoding utf8
        Write-Host "  $hive -> $hive.rr3.txt"
    }
}
$sysHive = Join-Path $cfgDir "SYSTEM"
if (Test-Path $sysHive) {
    & $RipExe -r $sysHive -p svc 2>$null | Out-File (Join-Path $OutDir "services.rr3.csv") -Encoding utf8
    Run $AppCompat @("-f", $sysHive, "--csv", $OutDir, "--csvf", "Shimcache.appcompatparser.csv")
}

# -- 3. REGBACK HIVES ---------------------------------------------------------
Write-Host "\`n[3/9] RegBack hives..."
$regBack = Join-Path $SrcC "Windows\\System32\\config\\RegBack"
if (Test-Path $regBack) {
    foreach ($hive in @("SAM","SOFTWARE","SYSTEM","SECURITY")) {
        $src = Join-Path $regBack $hive
        if (Test-Path $src) {
            & $RipExe -r $src -a 2>$null | Out-File (Join-Path $ParsedOSHives "$hive.RegBack.rr3.txt") -Encoding utf8
        }
    }
}

# -- 4. POWERSHELL HISTORY ----------------------------------------------------
Write-Host "\`n[4/9] PowerShell history..."
Get-ChildItem (Join-Path $SrcC "Users") -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    $src = Join-Path $_.FullName "AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt"
    if (Test-Path $src) {
        Copy-Item $src (Join-Path $OutDir "$($_.Name).ConsoleHost_history.txt") -Force
    }
}

# -- 5. WINDOWS SEARCH + WMI --------------------------------------------------
Write-Host "\`n[5/9] Windows Search + WMI persistence..."
$searchDir = Join-Path $SrcC "ProgramData\\Microsoft\\Search\\Data\\Applications\\Windows"
if ((Test-Path $SidrExe) -and (Test-Path $searchDir)) {
    Push-Location $searchDir
    & $SidrExe -f csv -r to-file -o $OutDir .\\
    Pop-Location
}
$objData = Join-Path $SrcC "Windows\\System32\\wbem\\Repository\\OBJECTS.DATA"
if ((Test-Path $Py27) -and (Test-Path $objData)) {
    if (Test-Path $PyWmi) { & $Py27 $PyWmi $objData | Out-File (Join-Path $OutDir "WMI-PersistenceFinder.txt") -Encoding utf8 }
    if (Test-Path $PyCcm) { & $Py27 $PyCcm -i $objData -o (Join-Path $OutDir "WMI-CCMRUAFinder.txt") }
}

# -- 6. EVTX / AMCACHE / SUM --------------------------------------------------
Write-Host "\`n[6/9] EvtxECmd / Amcache / SUM..."
$evtxLogs = Join-Path $SrcC "Windows\\System32\\winevt\\Logs"
if (Test-Path $evtxLogs) {
    Run $EvtxExe @("-d", $evtxLogs, "--csv", $OutDir, "--csvf", "_EVTX_$Host-all.csv")
}
$amcache = Join-Path $SrcC "Windows\\AppCompat\\Programs\\Amcache.hve"
if (Test-Path $amcache) { Run $Amcache @("-f", $amcache, "--csv", $OutDir) }

$sumDir = Join-Path $SrcC "Windows\\System32\\LogFiles\\Sum"
if (Test-Path $sumDir) {
    Push-Location $sumDir
    & esentutl.exe /p Current.mdb /o 2>&1 | Out-Null
    Pop-Location
    Run $SumExe @("-d", $sumDir, "--csv", $OutDir)
}

# -- 7. CHAINSAW + HAYABUSA + TAKAJO ------------------------------------------
Write-Host "\`n[7/9] Chainsaw / Hayabusa / Takajo..."
if (Test-Path $evtxLogs) {
    $sigmaDir = Join-Path $ToolsDir "chainsaw\\sigma"
    $mapping  = Join-Path $ToolsDir "chainsaw\\mappings\\sigma-event-logs-all.yml"
    $rulesDir = Join-Path $ToolsDir "chainsaw\\rules"
    Run $ChainsawExe @("hunt", $evtxLogs, "-s", $sigmaDir, "--mapping", $mapping, "-r", $rulesDir, "--csv", "--full", "--metadata", "-o", (Join-Path $OutDir "chainsaw-all"), "-q", "--skip-errors")

    Run $HayaExe @("csv-timeline", "--directory", $evtxLogs, "-s", "-w", "-a", "-b", "-o", (Join-Path $OutDir "Hayabusa-all.csv"), "-p", "standard", "-X", "-U", "-q")
    Run $HayaExe @("logon-summary", "--directory", $evtxLogs, "-q", "-X", "-K", "-U", "-o", (Join-Path $OutDir "Hayabusa-logon-summary"))
    Run $HayaExe @("computer-metrics", "--directory", $evtxLogs, "-q", "-K", "-o", (Join-Path $OutDir "Hayabusa-computer-metrics.csv"))
    Run $HayaExe @("extract-base64", "--directory", $evtxLogs, "-q", "-K", "-U", "-o", (Join-Path $OutDir "Hayabusa-extract-base64.csv"))

    $jsonOut = Join-Path $OutDir "Hayabusa-json-output.jsonl"
    Run $HayaExe @("json-timeline", "--directory", $evtxLogs, "-U", "-L", "-o", $jsonOut, "-w")
    if (Test-Path $jsonOut) {
        Run $TakajoExe @("extract-scriptblocks", "-t", $jsonOut, "-o", $ScriptBlocksDir)
    }
}

# -- 8. SRUM ------------------------------------------------------------------
Write-Host "\`n[8/9] SRUM..."
$sruDb = Join-Path $SrcC "Windows\\System32\\sru\\SRUDB.dat"
if (Test-Path $sruDb) {
    Push-Location (Split-Path $sruDb)
    & esentutl.exe /p SRUDB.dat /o 2>&1 | Out-Null
    Pop-Location
    $swHive = Join-Path $SrcC "Windows\\System32\\config\\SOFTWARE"
    $args = @("-f", $sruDb, "--csv", $OutDir)
    if (Test-Path $swHive) { $args += @("-r", $swHive) }
    Run $SrumExe $args
}

# -- 9. MFT / USN JOURNAL -----------------------------------------------------
Write-Host "\`n[9/9] MFT / USN Journal..."
$mftPath = Join-Path $SrcC "\$Extend\\\$MFT"
$usnPath = Join-Path $SrcC "\$Extend\\\$UsnJrnl\$J"
if (Test-Path $mftPath) {
    Run $MFTExe @("-f", $mftPath, "--csv", $OutDir, "--csvf", "MFTECmd_MFT_Output.csv")
}
if ((Test-Path $usnPath) -and (Test-Path $mftPath)) {
    Run $MFTExe @("-f", $usnPath, "-m", $mftPath, "--csv", $OutDir, "--csvf", "MFTECmd_J_Output.csv")
}

Write-Host "\`nDone. Output: $OutDir"
Write-Host "Press any key to close..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
`;
}

function _cypferRender() {
  const v = _cypferState;
  return v.mode === 'live' ? _cypferRenderLive(v) : _cypferRenderImage(v);
}

// ── RENDER UI ─────────────────────────────────────────────────────────────────

// Modal open/close -- reuses the same form UI as the Cypfer tab. Target flag
// lets rCypfer know which container to paint into.
let _cypferTarget = 'cypferContent';   // or 'cypferModalBody'

function openCypferModal() {
  _cypferTarget = 'cypferModalBody';
  document.getElementById('cypferOverlay').classList.add('open');
  rCypfer();
}
function closeCypferModal() {
  document.getElementById('cypferOverlay').classList.remove('open');
  _cypferTarget = 'cypferContent';
}

function rCypfer() {
  // If the Cypfer tab is active and the modal isn't open, paint into the tab
  const modalOpen = document.getElementById('cypferOverlay')?.classList.contains('open');
  const tabActive = document.querySelector('.tab.active')?.dataset.tab === 'cypfer';
  if (tabActive && !modalOpen) _cypferTarget = 'cypferContent';
  const el = document.getElementById(_cypferTarget);
  if (!el) return;
  const v = _cypferState;
  const isImage = v.mode === 'image';

  el.innerHTML = `
    <div class="chart-box" style="margin-bottom:14px">
      <div class="chart-header">
        <span class="chart-title">EventScope Cypfer &mdash; Collector Script Generator</span>
      </div>
      <div style="font-size:11px;color:var(--text-dim);font-family:var(--mono);margin-bottom:14px;line-height:1.7">
        Generates a ready-to-run PowerShell triage script customised to your paths. Pick a mode, fill in the fields, then copy or download the script. Paste it into VS Code or any elevated PowerShell and run.
        <br>Nothing in this tab executes anything on your machine &mdash; it's a pure text generator. Respects the air-gap rules.
      </div>

      <!-- Mode toggle -->
      <div style="display:flex;gap:10px;margin-bottom:16px">
        <button class="chart-btn${v.mode==='live'?' active':''}"  onclick="setCypferMode('live')">Live System</button>
        <button class="chart-btn${v.mode==='image'?' active':''}" onclick="setCypferMode('image')">Forensic Image (mounted C:)</button>
      </div>

      <!-- Form -->
      <div style="display:grid;grid-template-columns:160px 1fr;gap:8px 12px;margin-bottom:16px;align-items:center">
        ${isImage ? `
          <label style="font-family:var(--mono);font-size:11px;color:var(--text-dim)">Case name</label>
          <input class="filter-input" id="cypferCase"   value="${eH(v.caseName)}"  oninput="updateCypfer('caseName',this.value)"  style="font-family:var(--mono)">

          <label style="font-family:var(--mono);font-size:11px;color:var(--text-dim)">Host label</label>
          <input class="filter-input" id="cypferHost"   value="${eH(v.hostLabel)}" oninput="updateCypfer('hostLabel',this.value)" style="font-family:var(--mono)">

          <label style="font-family:var(--mono);font-size:11px;color:var(--text-dim)">Source C: folder</label>
          <input class="filter-input" id="cypferSrcC"   value="${eH(v.sourceC)}"   oninput="updateCypfer('sourceC',this.value)"   style="font-family:var(--mono)" placeholder="D:\\CaseAnalysis\\case-001\\HOSTNAME\\C">

          <label style="font-family:var(--mono);font-size:11px;color:var(--text-dim)">Case output dir</label>
          <input class="filter-input" id="cypferCaseDir" value="${eH(v.caseDir)}"  oninput="updateCypfer('caseDir',this.value)"   style="font-family:var(--mono)" placeholder="D:\\CaseAnalysis\\case-001\\HOSTNAME">
        ` : `
          <label style="font-family:var(--mono);font-size:11px;color:var(--text-dim)">Output dir</label>
          <input class="filter-input" id="cypferOutDir" value="${eH(v.outDir)}" oninput="updateCypfer('outDir',this.value)" style="font-family:var(--mono)" placeholder="C:\\eventscope\\output">
        `}

        <label style="font-family:var(--mono);font-size:11px;color:var(--text-dim)">Tools dir</label>
        <input class="filter-input" id="cypferToolsDir" value="${eH(v.toolsDir)}" oninput="updateCypfer('toolsDir',this.value)" style="font-family:var(--mono)" placeholder="C:\\Tools">
      </div>

      <!-- Action buttons -->
      <div style="display:flex;gap:10px;margin-bottom:14px">
        <button class="copy-btn" style="font-size:12px;padding:6px 14px" onclick="copyCypferScript()">Copy to Clipboard</button>
        <button class="copy-btn" style="font-size:12px;padding:6px 14px" onclick="downloadCypferScript()">&darr; Download .ps1</button>
        <span id="cypferStats" style="margin-left:auto;align-self:center;font-size:11px;font-family:var(--mono);color:var(--text-dim)"></span>
      </div>

      <!-- Preview -->
      <div style="font-size:11px;color:var(--text-dim);font-family:var(--mono);margin-bottom:4px">Preview:</div>
      <textarea id="cypferPreview" readonly style="width:100%;height:420px;font-family:var(--mono);font-size:11px;background:var(--surface2);color:var(--text);border:1px solid var(--border);border-radius:4px;padding:10px;resize:vertical;white-space:pre;overflow:auto"></textarea>
    </div>
  `;

  _cypferUpdatePreview();
}

function _cypferUpdatePreview() {
  const ta = document.getElementById('cypferPreview');
  if (!ta) return;
  const text = _cypferRender();
  ta.value = text;
  const stats = document.getElementById('cypferStats');
  if (stats) {
    const lines = text.split('\n').length;
    stats.textContent = `${lines.toLocaleString()} lines \u2022 ${text.length.toLocaleString()} chars`;
  }
}

// ── EVENT HANDLERS ────────────────────────────────────────────────────────────

function setCypferMode(mode) {
  _cypferState.mode = mode;
  rCypfer();
}

function updateCypfer(key, val) {
  _cypferState[key] = val;
  _cypferUpdatePreview();
}

function copyCypferScript() {
  const text = _cypferRender();
  navigator.clipboard.writeText(text).then(
    () => showToast('Collector script copied to clipboard'),
    () => showToast('Clipboard copy failed')
  );
}

function downloadCypferScript() {
  const text = _cypferRender();
  const name = _cypferState.mode === 'live'
    ? 'collect-local.ps1'
    : `collect-image-${_cypferState.caseName || 'case'}-${_cypferState.hostLabel || 'host'}.ps1`;
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  showToast(`Downloaded ${name}`);
}
